### ISSUE TITLE
block the rest of the debug onEnable that i think u forgot 

### ISSUE THREAD

**Issue by EzWzs** [dieterblancke/BungeeUtilisalsX#123]
This debug info should only be present on debug: true in config 

![image](https://user-images.githubusercontent.com/60761665/128737131-4090ed7c-bfbd-44f2-a9b9-45792019d2db.png)
also the part where it says enabled plugin thats duplicated you already mentioned that at first load

1 more thing if u could comment here how i change the idleTimeout message so it doesnt show

**Comment by dieterblancke** [comment]
- I personally would prefer it not to be considered as debug info to see which files did and did not load properly but okay ...
- What do you mean with part that is duplicated?
- if you read the message, idleTimeout should be lower, or maxLifetime should be higher, this was actually not configurable as I noticed so I added an option just now, though this is on the very very experimental RabbitMQ branch on which I'm reworking some commands for multiproxy support through job layers. It will take a while till I release that branch.

**Comment by dieterblancke** [comment]
Removed config debug now in rabbitmq branch which I plan on merging later this week, added an idleTimeout configuration option aswell, but I don't get yet what you mean with duplicated load message.

**Comment by EzWzs** [comment]
nvm they are different one says load and one says enable im dumb

**Comment by dieterblancke** [comment]
> nvm they are different one says load and one says enable im dumb

yes and they're not BuX messages but rather BungeeCord messages so I cannot fix them either way
