### ISSUE TITLE
[FEATURE] can you add an option to bypass the blocked commands

### ISSUE THREAD

**Issue by EzWzs** [dieterblancke/BungeeUtilisalsX#128]
just how u did with the subcommands just add like 
 permission: some.permission

**Comment by EzWzs** [comment]
also i found a bug when u dont use the subcommands it still shows blocked in "lobby server" even though its blocked globally

![image](https://user-images.githubusercontent.com/60761665/129380864-663d605d-a9e1-44d7-8ce3-9e8075a2315c.png)
![image](https://user-images.githubusercontent.com/60761665/129380901-e72b7188-a7e6-4cf0-b6bd-4c113d522b48.png)

**Comment by dieterblancke** [comment]
> also i found a bug when u dont use the subcommands it still shows blocked in "lobby server" even though its blocked globally
> 
> ![image](https://user-images.githubusercontent.com/60761665/129380864-663d605d-a9e1-44d7-8ce3-9e8075a2315c.png)
> ![image](https://user-images.githubusercontent.com/60761665/129380901-e72b7188-a7e6-4cf0-b6bd-4c113d522b48.png)

ah I think that's normal behaviour though, the message is in the language file and uses the {server} placeholder which gives the current server of the user.
