### ISSUE TITLE
[FEATURE] 3 features

### ISSUE THREAD

**Issue by EzWzs** [dieterblancke/BungeeUtilisalsX#137]
1. remove /f accept, is useless as doing /friend add on a friend request already adds the person.
2. remove /f removerequest and /f deny for the same reasons as /f accept if suggestion 3 is made.
3. make it so if a player is not your friend and you do /f remove it removes the outgoing friend request (/f removerequest) and if a player sent a request and you do /f remove it removes the incoming friend request (/f deny)

**Comment by dieterblancke** [comment]
> 1. remove /f accept, is useless as doing /friend add on a friend request already adds the person.
> 2. remove /f removerequest and /f deny for the same reasons as /f accept if suggestion 3 is made.
> 3. make it so if a player is not your friend and you do /f remove it removes the outgoing friend request (/f removerequest) and if a player sent a request and you do /f remove it removes the incoming friend request (/f deny)

1) BungeeUtilisalsX is a general solution, some people would rather have this command still available, so it will stay (and behind the screens, /friend add on friend request just executes /friend accept anyway)
2) Same argumentation as above
3) I'll add this to my todo I guess (though I'm not the biggest fan of it, creates both more and less confusion in a way)

For 1 and 2, you should just disable the sub commands in question.
