### ISSUE TITLE
[FEATURE] Time zones for placeholders

### ISSUE THREAD

**Issue by Turtle418** [dieterblancke/BungeeUtilisalsX#156]
make the placeholders hook into a selected time zone in a config

**Comment by dieterblancke** [comment]
As an update on this, which placeholders would you expect to hook into this timezone? I recommend changing your system timezone instead, if possible.

**Comment by Turtle418** [comment]
{timeleft: targetTime}, {date}, {time}, and {datetime}
sorry for the late reply.
