### ISSUE TITLE
Configurable Friends Settings names bug

### ISSUE THREAD

**Issue by TadiklCZE** [dieterblancke/BungeeUtilisalsX#165]
Hey! I have just translated the names of the friends settings, but it seems like it also translated it for identifiers... When I use a placeholder in a command when I click on a message from BUX, it replaces the placeholder to translated word so the command then doesnt work...

**Comment by dieterblancke** [comment]
Could you please describe this issue a bit more with possibly configuration settings and images?

**Comment by TadiklCZE** [comment]
> Could you please describe this issue a bit more with possibly configuration settings and images?

When I changed the names of the settings, it uses the Translated names in the setting placeholder. So when you use the placeholder in command, to change the setting by clicking on a message, it doesn't work, because the setting name is incorrect.
