### ISSUE TITLE
[FEATURE] Admin Chat - an alternative to staff chat

### ISSUE THREAD

**Issue by xenforq** [dieterblancke/BungeeUtilisalsX#40]
There is one explanation and one explanation only, and that is the short one. Admin-chat is an alternative to staff-chat that uses other permissions for access to the chat. 
You may look at any of these "cores" for examples of how an admin-chat works and looks like.

**Comment by dieterblancke** [comment]
@xenforq is this still needed? If yes, I'll start on it right after your reply.

**Comment by xenforq** [comment]
> @xenforq is this still needed? If yes, I'll start on it right after your reply.

Someone else might want this feature, but personally, it is nothing I'd even have the chance to utilize in my current stance.

**Comment by dieterblancke** [comment]
> 
> 
> > @xenforq is this still needed? If yes, I'll start on it right after your reply.
> 
> Someone else might want this feature, but personally, it is nothing I'd even have the chance to utilize in my current stance.

Thank you for your quick reply. I'll close this feature request for now then.
