### ISSUE TITLE
[FEATURE] Logical auto-announcements

### ISSUE THREAD

**Issue by xenforq** [dieterblancke/BungeeUtilisalsX#44]
BUX in its current state with the auto-announcer; it goes through the list of announcements 1-by-1, no matter what servers or server groups you've decided to pick. This can leave your network looking pretty blank at specific servers. Currently the delays you may experience visually with the auto-announcer can be a bit annoying and strange looking at times.

**Solution to this issue;**
Adding a toggleable boolean option in the configuration for the auto-announcers letting you select server/server groups to be grouped separately would fix this visual delay seen in chat.

**Comment by dieterblancke** [comment]
See implementation in https://github.com/dieterblancke/BungeeUtilisalsX/commit/2949e31485b498c5db0099b390cee2a6f8a3c746

**Comment by xenforq** [comment]
> See implementation in [2949e31](https://github.com/dieterblancke/BungeeUtilisalsX/commit/2949e31485b498c5db0099b390cee2a6f8a3c746)

The feature works exactly as planned, thank you for the implementation.
