### ISSUE TITLE
[FEATURE] Staffrollback command

### ISSUE THREAD

**Issue by MoonSoD** [dieterblancke/BungeeUtilisalsX#57]
**Is your feature request related to a problem? Please describe.**
Well, there are still a few cases of abuse.

**Describe the solution you'd like**
Would be nice to add a command to remove the history of punishments a staff member has granted.
e.g.: ```/staffrollback <playerName> <time>```

**Comment by dieterblancke** [comment]
Now I am getting closer to implementing this feature, could you please explain what you want exactly?

Should it permanently remove the punishments of that staff member OR only set the "active" status to false of all of these?

I am, personally, thinking of adding a parameter option for example:

/staffrollback (playerName) (time) -> this will set the status of all punishments executed by this player in X time to active: false
/staffrollback (playerName) (time) -f -> -f stands for force, this would completely delete the punishments from the database (making it so the data is not available anymore). This -f option would ofcourse need additional permissions.

**Comment by MoonSoD** [comment]
Yeah, that's a flexible solution, perfect
