### ISSUE TITLE
[BUG] Commandspy own players commands bug

### ISSUE THREAD

**Issue by EzWzs** [dieterblancke/BungeeUtilisalsX#89]
**Describe the bug**
When using /commandspy it shows the own players commands

**To Reproduce**
1. Turn on commandspy command in generalcommands.yml and run a command
**Expected behavior**
I expect it not to show the players commands but still show everyone elses

**Screenshots**

**Versions:**
 - BUX 1.2.2, Flamecord 0.5.3, Any client bug still happens

**Comment by dieterblancke** [comment]
I don't know if I said this before, but this is intended behavior. Commandspy was designed to show all commands that are being executed, including your own commands.

I guess I could make an option for it, but yeah.

**Comment by EzWzs** [comment]
an option would be nice for people that dont want it, it just seems repeitivite

**Comment by dieterblancke** [comment]
Decided not to make a config option and just filter the own user out, a working build can now be found in the CI actions tab.
