### ISSUE TITLE
[FEATURE] Add vanish support to private messages

### ISSUE THREAD

**Issue by EzWzs** [dieterblancke/BungeeUtilisalsX#90]
**Is your feature request related to a problem? Please describe.**
Sort of, it is a problem because it removes the point of being in vanish since a  normal player or hacker wants to find a staff member is online or not they can just msg a staff member and even if they are in vanish it will show sent.

**Describe the solution you'd like**
When a player is vanished, send a message like player not found (u can use supervanish/premiumvanish api for this, you already did with djp+)

**Comment by dieterblancke** [comment]
If I add support for this, it would only be with PremiumVanish: https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/

**Comment by EzWzs** [comment]
yes i have premiumvanish i have that so it would be perfect
