### ISSUE TITLE
[FEATURE] Add an internal {status} placeholder for /f list

### ISSUE THREAD

**Issue by EzWzs** [dieterblancke/BungeeUtilisalsX#95]
Problem/solution:
When a player is in your friend list, and he is offline it will show the last time offline, but I would like it to show something like
Player online: online, Player offline: offline

This already sort of seems to be there as this
status:
  online: online
  offline: offline
  but i dont know how to use it or if its even there

**Comment by dieterblancke** [comment]
The placeholder for this should be:
`{online}`

Try it out and see if it works, if it does, please close this ticket^^

**Comment by EzWzs** [comment]
fixed
