### ISSUE TITLE
[BUG] /staffhistory shows incorrect name in header

### ISSUE THREAD

**Issue by EzWzs** [dieterblancke/BungeeUtilisalsX#97]
**Describe the bug**
when running /staffhistory <another staff member> it shows the own player's name in the header where it should show the player being investigated (the other staff member)

MyCode:
'&6Staff Punishment History of {user} &b({currentPage} of {maxPages})'

the {user} placeholder is whats showing incorrectly and {by} does nothing

**Comment by dieterblancke** [comment]
Added this in the latest build
