### ISSUE TITLE
[BUG] ban id always shows -1

### ISSUE THREAD

**Issue by EzWzs** [dieterblancke/BungeeUtilisalsX#98]
**Describe the bug**
This could be a bug or a mistake on my part but when a player gets banned it should generate a random set of characters and numbers to show a ban ID making it very easy to find a specific ban but when a player gets banned it always shows -1

MY CONFIG (punishments/config.yml)
https://pastebin.com/NhAAWawc

I AM USING THE {id} placeholder

please tell me if there is any more information you need

**Comment by dieterblancke** [comment]
Please use the `{punishment_uid}` placeholder instead.
